name: VSC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#e0e0e0'
    - '#777777'
    - '#575757'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose:
  - name: awareness
    item: null
    url: null
